### ISSUE TITLE
Notes on README-DEV.adoc

### ISSUE THREAD

**Issue by syedriko** [redhat-developer-demos/knative-tutorial#119]
1. Should we make README-DEV.adoc a regular text file README-DEV.txt, given it describes how to generate human-readable text from asciidoc?
2. It seems we need to lose the -g from the 'npm install' or we don't get the node_modules directory the doc refers to in the end
3. We need to add the following to dev-site.yml
```
asciidoc:
  attributes:
    tutorial-namespace: knativetutorial
  extensions:
    - ./lib/copy-to-clipboard.js
```
4. "open the server index in a browser" does not happen for me on Fedora, I need to manually browse http://localhost:5353
5. why not add dev-site.yml as a file to the project and remove its contents from README-DEV?
6. "automatically update the HTML when the asciidoc source changes." Sometimes, I'm not seeing HTML updates in the browser, even though the HTML in gh-pages is updated. Cleaning browser's cache fixes this.
