### ISSUE TITLE
Let's use higher versions of the provided CRDs

### ISSUE THREAD

**Issue by matzew** [redhat-developer-demos/knative-tutorial#244]
**Describe the bug**

* old version: https://github.com/redhat-developer-demos/knative-tutorial/blob/master/eventing/eventinghello-source.yaml#L1
Let's use `v1beta1`

* the yaml says `v1` already for channel: https://github.com/redhat-developer-demos/knative-tutorial/blob/staging/eventing/channel.yaml#L1

**BUT** the text says still `v1beta1`: https://redhat-developer-docs.github.io/knative-tutorial-staging/knative-tutorial/eventing/channel-and-subscribers.html#eventing-create-event-channel

* same with Subscription: still uses BETA, in https://redhat-developer-docs.github.io/knative-tutorial-staging/knative-tutorial/eventing/channel-and-subscribers.html#eventing-create-subscriber

```yaml
apiVersion: messaging.knative.dev/v1beta1
kind: Subscription
....
```

* Same with trigger, in https://redhat-developer-docs.github.io/knative-tutorial-staging/knative-tutorial/eventing/eventing-trigger-broker.html
```yaml
apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
...
```
